In [1]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt

# Create Incident Event Log

In [2]:
incident_events = [
    {"time": "10:00", "event": "Bias monitoring alert triggered", "severity": "SEV-2"},
    {"time": "10:07", "event": "Incident Commander assigned", "severity": "SEV-2"},
    {"time": "10:18", "event": "Containment: Model rollback initiated", "severity": "SEV-2"},
    {"time": "11:05", "event": "Impact wider than expected", "severity": "SEV-1"},
    {"time": "11:40", "event": "Investigation: Root cause analysis started", "severity": "SEV-1"},
    {"time": "14:10", "event": "Mitigation: Guardrail patch deployed", "severity": "SEV-2"},
    {"time": "16:00", "event": "System stabilized", "severity": "SEV-3"},
]

df = pd.DataFrame(incident_events)
df

    time                                       event severity
0  10:00             Bias monitoring alert triggered    SEV-2
1  10:07                 Incident Commander assigned    SEV-2
2  10:18       Containment: Model rollback initiated    SEV-2
3  11:05                  Impact wider than expected    SEV-1
4  11:40  Investigation: Root cause analysis started    SEV-1
5  14:10        Mitigation: Guardrail patch deployed    SEV-2
6  16:00                           System stabilized    SEV-3

# Convert Time → Timestamp

In [3]:
base_date = datetime.today().date()

df["timestamp"] = df["time"].apply(
    lambda t: datetime.strptime(f"{base_date} {t}", "%Y-%m-%d %H:%M")
)

df

,time,event,severity,timestamp
0,10:00,Bias monitoring alert triggered,SEV-2,2026-02-21 10:00:00
1,10:07,Incident Commander assigned,SEV-2,2026-02-21 10:07:00
2,10:18,Containment: Model rollback initiated,SEV-2,2026-02-21 10:18:00
3,11:05,Impact wider than expected,SEV-1,2026-02-21 11:05:00
4,11:40,Investigation: Root cause analysis started,SEV-1,2026-02-21 11:40:00
5,14:10,Mitigation: Guardrail patch deployed,SEV-2,2026-02-21 14:10:00
6,16:00,System stabilized,SEV-3,2026-02-21 16:00:00

# Calculate Minutes from Incident Start

In [4]:
df["minutes_from_start"] = (
    df["timestamp"] - df["timestamp"].iloc[0]
).dt.total_seconds() / 60

df

,time,event,severity,timestamp,minutes_from_start
0,10:00,Bias monitoring alert triggered,SEV-2,2026-02-21 10:00:00,0.0
1,10:07,Incident Commander assigned,SEV-2,2026-02-21 10:07:00,7.0
2,10:18,Containment: Model rollback initiated,SEV-2,2026-02-21 10:18:00,18.0
3,11:05,Impact wider than expected,SEV-1,2026-02-21 11:05:00,65.0
4,11:40,Investigation: Root cause analysis started,SEV-1,2026-02-21 11:40:00,100.0
5,14:10,Mitigation: Guardrail patch deployed,SEV-2,2026-02-21 14:10:00,250.0
6,16:00,System stabilized,SEV-3,2026-02-21 16:00:00,360.0

# Severity Escalation Summary

In [6]:
severity_counts = df["severity"].value_counts()
severity_counts

severity
SEV-2    4
SEV-1    2
SEV-3    1
Name: count, dtype: int64

# Key Effectiveness Metrics

In [7]:
containment_time = df[df["event"].str.contains("Containment")]["minutes_from_start"].values[0]
investigation_time = df[df["event"].str.contains("Investigation")]["minutes_from_start"].values[0]
mitigation_time = df[df["event"].str.contains("Mitigation")]["minutes_from_start"].values[0]

print("Time to Containment:", containment_time, "minutes")
print("Time to Investigation:", investigation_time, "minutes")
print("Time to Mitigation:", mitigation_time, "minutes")

⏱ Time to Containment: 18.0 minutes
🔍 Time to Investigation: 100.0 minutes
🛠 Time to Mitigation: 250.0 minutes